ZoomRoom plugin - Convert for JWT to OAuth
KingdomFirst/RockAssemblies pull request #111
Opened 2023-01-04 22:09 UTC by guymaness2

### Description 

##### What does the change add or fix?

Zoom is deprecating JWT authentication to their api in June 2023. These changes convert the plugin interface from using JWT to Zoom's Server-to-Server OAuth authentication.  

---------

### Release Notes 

##### What does the change add or fix in a succinct statement that will be read by clients?

* Update plugin to use Server-to-Server OAuth authentication instead of JWT. 

---------

### Requested By

##### Who reported, requested, or paid for the change?

FPG

---------

### Screenshots

##### Does this update or add options to the block UI?

no

---------

### Change Log

##### What files does it affect?

* ZoomDotNetFramework/Responses/OauthErrorResponse.cs
* ZoomDotNetFramework/Responses/OauthTokenResponse.cs
* ZoomDotNetFramework/ZoomApi.cs
* ZoomDotNetFramework/ZoomDotNetFramework.csproj
* rocks.kfs.Zoom/Migrations/009_UpdateApiAttributesForOauth.cs
* rocks.kfs.Zoom/Settings.cs
* rocks.kfs.Zoom/Zoom.cs
* rocks.kfs.Zoom/rocks.kfs.Zoom.csproj

---------

### Migrations/External Impacts

##### Is it a breaking change for other versions/clients?

https://github.com/KingdomFirst/RockBlocks/pull/129 is dependent on this change

2023-01-05 17:29 UTC, guymaness2 commented on ZoomDotNetFramework/Responses/OauthTokenResponse.cs
> +// Copyright 2021 by Kingdom First Solutions
```suggestion
// Copyright 2023 by Kingdom First Solutions
```

2023-01-05 17:34 UTC, guymaness2 commented on ZoomDotNetFramework/ZoomApi.cs
> +            request.AddHeader( "authorization", "Bearer " + _oAuthToken ); // used on every request
```suggestion
            request.AddHeader( "authorization", "Bearer " + _oAuthToken );
```

2023-01-05 17:39 UTC, guymaness2 commented on rocks.kfs.Zoom/Migrations/009_UpdateApiAttributesForOauth.cs
> +            // Create new Zoom OAuth App attributes
Delete old attributes as well

2023-01-05 17:57 UTC, guymaness2 commented on rocks.kfs.Zoom/Migrations/009_UpdateApiAttributesForOauth.cs
> +        }
Looks like Room Reservation ReservationType model may have changed. Client having CreateDB migration errors. Need to look into issue and fix.

2023-01-05 18:29 UTC, guymaness2 commented on rocks.kfs.Zoom/Zoom.cs
> +            var zoomRoomsToDelete = zoomRoomDV.Where( v => !zrIds.Contains( v.Value ) );
```suggestion
            var zrIds = zrList.Select( zr => zr.Zr_Id ).ToList();
            var zoomRoomsToDelete = zoomRoomDV.Where( v => !zrIds.Contains( v.Value ) );
```

2023-01-05 18:44 UTC, nateh777 requested changes
Changes in comments from Guy.

2023-01-11 19:30 UTC, guymaness2 commented on rocks.kfs.Zoom/Migrations/009_UpdateApiAttributesForOauth.cs
> +        }
Fixed

2023-01-11 21:53 UTC, guymaness2 commented on rocks.kfs.Zoom/Migrations/009_UpdateApiAttributesForOauth.cs
> +            // Create new Zoom OAuth App attributes
done

2023-01-24 17:04 UTC, nateh777 commented
Let's remove libs/com.centralaz.roommanagement.dll, not necessary if we do not reference it in any of our projects.

2023-01-24 17:05 UTC, nateh777 commented on ZoomDotNetFramework/Enums/RoomStatus.cs
> +// Copyright 2021 by Kingdom First Solutions
```suggestion
// Copyright 2023 by Kingdom First Solutions
```

2023-01-24 17:06 UTC, nateh777 commented on ZoomDotNetFramework/Responses/ListRoomsResponse.cs
> +// Copyright 2021 by Kingdom First Solutions
```suggestion
// Copyright 2023 by Kingdom First Solutions
```

2023-01-24 17:06 UTC, nateh777 commented on ZoomDotNetFramework/Responses/ListRoomsResponse.cs
> +
```suggestion
```

2023-01-24 17:12 UTC, nateh777 commented on ZoomDotNetFramework/ZoomApi.cs
> +                request.AddParameter( "unassigned_rooms", pageSizeInt );
```suggestion
                request.AddParameter( "page_size", pageSizeInt );
```

2023-01-24 17:25 UTC, nateh777 submitted a review, later dismissed

2023-01-24 17:33 UTC, nateh777 approved these changes

2023-01-24 17:34 UTC, merged