Combine items for Microsoft Utils plugin
KingdomFirst/RockAssemblies pull request #114
Opened 2023-01-26 21:21 UTC by guymaness2

### Description 
Cleaned up and moved some code to better facilitate the new package.  
  
##### What does the change add or fix?

See release notes

---------

### Release Notes 

##### What does the change add or fix in a succinct statement that will be read by clients?

Combined rocks.KFS.WorkflowFromEWSAccount and rocks.KFS.Shortcodes assemblies int a single new assembly named rocks.KFS.Microsoft365Utilities.

---------

### Requested By

##### Who reported, requested, or paid for the change?

internal

---------

### Screenshots

##### Does this update or add options to the block UI?

no

---------

### Change Log

##### What files does it affect?

* rocks.kfs.WorkflowFromEWS/Jobs/LaunchWorkflowFromEWSAccount.cs → rocks.kfs.Microsoft365Utilities/Jobs/LaunchWorkflowFromEWSAccount.cs 
*  rocks.kfs.WorkflowFromEWS/Migrations/002_CreateAzureAppAttributes.cs → rocks.kfs.Microsoft365Utilities/Migrations/001_CreateEWSAttributes.cs
* rocks.kfs.WorkflowFromEWS/Properties/AssemblyInfo.cs → rocks.kfs.Microsoft365Utilities/Properties/AssemblyInfo.cs
* rocks.kfs.Shortcodes/EWS/CalendarItems.cs → rocks.kfs.Microsoft365Utilities/Shortcodes/CalendarItems.cs
* rocks.kfs.Shortcodes/packages.config → rocks.kfs.Microsoft365Utilities/packages.config
* rocks.kfs.WorkflowFromEWS/rocks.kfs.WorkflowFromEWS.csproj → rocks.kfs.Microsoft365Utilities/rocks.kfs.Microsoft365Utilities.csproj
* rocks.kfs.Shortcodes/Migrations/001_CreateAttribute.cs - DELETED
* rocks.kfs.Shortcodes/Properties/AssemblyInfo.cs - DELETED
* rocks.kfs.Shortcodes/rocks.kfs.Shortcodes.csproj - DELETED
* rocks.kfs.WorkflowFromEWS/packages.config

---------

### Migrations/External Impacts

##### Is it a breaking change for other versions/clients?

no

2023-01-27 18:16 UTC, nateh777 requested changes
All your changes look good. Since we are updating code, can you update the "Launch Workflows With" to remove "Default: Unread"

2023-01-30 21:21 UTC, guymaness2 commented on rocks.kfs.Microsoft365Utilities/ReadMe.md
> +![Kingdom First Solutions](Images/KFSBanner.jpg)
```suggestion
![KFSBanner](https://user-images.githubusercontent.com/7374281/215597774-44e515be-1aeb-4bae-94be-085827cced1d.jpg)
```

2023-01-30 21:23 UTC, guymaness2 commented on rocks.kfs.Microsoft365Utilities/ReadMe.md
> +![Shortcode List](Images/ShortcodeInList.png)
```suggestion
![Shortcode List](https://user-images.githubusercontent.com/7374281/215598075-d9498e71-5930-4ad6-a20d-b02397be0d6a.png)
```

2023-01-31 16:51 UTC, nateh777 approved these changes

2023-01-31 16:51 UTC, merged