Add support for Other Receipts to Intacct api model
KingdomFirst/RockAssemblies pull request #50
Opened 2021-11-09 17:44 UTC by guymaness2

### Description 

##### What does the change add or fix?

Enhanced KFS's Intacct api interface to support creation of Other Receipts in Intacct account.

---------

### Release Notes 

##### What does the change add or fix in a succinct statement that will be read by clients?

* Enhanced KFS's Intacct api interface to support creation of Other Receipts in Intacct account.

---------

### Requested By

##### Who reported, requested, or paid for the change?

River Point Church

---------

### Screenshots

##### Does this update or add options to the block UI?

See RockBlocks PR for details.

---------

### Change Log

##### What files does it affect?

* rocks.kfs.Intacct/Enums/PaymentMethod.cs
* rocks.kfs.Intacct/IntacctCheckingAccountList.cs
* rocks.kfs.Intacct/IntacctEndpoint.cs
* rocks.kfs.Intacct/IntacctModels.cs
* rocks.kfs.Intacct/IntacctOtherReceipt.cs
* rocks.kfs.Intacct/rocks.kfs.Intacct.csproj

---------

### Migrations/External Impacts

##### Is it a breaking change for other versions/clients?

none

2021-11-11 17:02 UTC, guymaness2 commented on rocks.kfs.Intacct/Enums/PaymentMethod.cs
> +        [Description( "Printed Check" )]
Add "Name" decorator and use Intacct UI nomenclature to use in Block.

2021-11-11 18:30 UTC, guymaness2 commented on rocks.kfs.Intacct/IntacctOtherReceipt.cs
> +                mergeFields.Add( "CustomDimensions", customDimensionValues );
Add field for "Summary" and pass the entire bTran object.

2021-11-11 18:30 UTC, guymaness2 commented on rocks.kfs.Intacct/IntacctOtherReceipt.cs
> +                    ClassId = classId
Need to set CustomFields property to customdimensions

2021-11-11 18:30 UTC, guymaness2 commented on rocks.kfs.Intacct/IntacctOtherReceipt.cs
> +        private List<string> GetCustomDimensions()
extract method for reuse

2021-11-16 17:57 UTC, nateh777 requested changes
@guymaness2 see comments on a few minor modifications. Also you tested both other receipts mode and regular export mode, correct? Just want to make sure.

2021-11-16 17:57 UTC, nateh777 commented on rocks.kfs.Intacct/Utils/TransactionHelpers.cs
> +// Copyright 2019 by Kingdom First Solutions
Update Copyright year

2021-11-16 17:57 UTC, nateh777 commented on rocks.kfs.Intacct/IntacctJournal.cs
> -                account.LoadAttributes();
Attributes still need to be loaded on the account, even though it gets passed into a method that runs the loadattributes method I am not sure if it updates the object at this level with the attributes, and is a bit weird and not readable to rely on that anyway. I would rather have it here still.

2021-11-16 17:57 UTC, nateh777 commented on rocks.kfs.Intacct/IntacctOtherReceipt.cs
> -                account.LoadAttributes();
Attributes still need to be loaded on the account, even though it gets passed into a method that runs the loadattributes method I am not sure if it updates the object at this level with the attributes, and is a bit weird and not readable to rely on that anyway. I would rather have it here still.

2021-11-16 17:57 UTC, nateh777 commented on rocks.kfs.Intacct/IntacctOtherReceipt.cs
> +                Dictionary<string, object> mergeFields = TransactionHelpers.GetMergeFieldsAndDimensions( ref debugLava, customDimensionValues, mergeFieldObjects );
Did you test the lava debug? If not, can you? Just make sure it goes into the method and comes back out okay? I am expecting it should, but just want to be sure.

2021-11-16 18:01 UTC, guymaness2 commented on rocks.kfs.Intacct/IntacctJournal.cs
> -                account.LoadAttributes();
@nateh777  Do you mean remove it from the method and put it back here, or bring it back here and leave it in both places?

2021-11-16 18:10 UTC, nateh777 commented on rocks.kfs.Intacct/IntacctJournal.cs
> -                account.LoadAttributes();
I think just bring the loadattributes at this level, then I don't think you will need it at the lower level, I think it is just clearer that way and more guaranteed to work compared to I am not sure if the other way goes back up. Though you could leave it in both places I don't think it is necessary.

2021-11-17 03:44 UTC, merged