WIP: Zoom Room Integration
KingdomFirst/RockAssemblies pull request #53
Opened 2021-12-21 15:58 UTC by guymaness2

**Thank you for your code contribution, we will take your code suggestion into consideration. It will be reviewed, and based on code quality and need addressed, we will determine acceptance. If this code addresses a feature request or issue, be sure to link to that issue.** 

### Description 

##### What does the change add or fix?

[Add a description here]

**New Settings:**

[Add a bulleted list of new settings here]

---------

### Release Notes 

##### What does the change add or fix in a succinct statement that will be read by clients?

[Add a bulleted list of release notes here]

---------

### Requested By

##### Who reported, requested, or paid for the change?

[Add the client here]

---------

### Screenshots

##### Does this update or add options to the block UI?

[Add a screenshot here]

---------

### Change Log

##### What files does it affect?

[Add a file list here]

---------

### Migrations/External Impacts

##### Is it a breaking change for other versions/clients?

[Add a no or yes with explanation here]

2021-12-21 17:29 UTC, guymaness2 commented on ZoomDotNetFramework/Entities/Meeting.cs
> +        public DateTime Start_Time { get; set; }
Try this as a DateTimeOffset

2021-12-21 17:32 UTC, guymaness2 commented on ZoomDotNetFramework/Entities/Meeting.cs
> +        public List<MeetingSetting> Settings { get; set; }
```suggestion
        public MeetingSetting Settings { get; set; }
```

2021-12-21 17:34 UTC, guymaness2 commented on ZoomDotNetFramework/Entities/Meeting.cs
> +    }
It appears this class may not be fully built out to match Zoom meeting object. Verify all pieces are accounted for.

2021-12-21 17:38 UTC, guymaness2 commented on ZoomDotNetFramework/Entities/TrackingField.cs
> +
```suggestion
```

2021-12-21 18:04 UTC, guymaness2 commented on ZoomDotNetFramework/Enums/PhoneNumbersLabel.cs
> +        [Description( "Mobile" )]
Only add descriptions where needed

2021-12-21 18:07 UTC, guymaness2 commented on ZoomDotNetFramework/Entities/ZoomRoom.cs
> +        public string Id { get; set; }
Definition appears to be incomplete. Need to match api object

2021-12-21 18:08 UTC, guymaness2 commented on ZoomDotNetFramework/Enums/RoomType.cs
> +    public enum RoomType
Where did this come from in the API? Verify it is valid and being used properly

2021-12-21 18:09 UTC, guymaness2 commented on ZoomDotNetFramework/Enums/UserAccountStatus.cs
> +        [Description( "Pending" )]
are descriptions needed?

2021-12-23 23:07 UTC, guymaness2 commented on ZoomDotNetFramework/Enums/RoomType.cs
> +    public enum RoomType
This is used on the ZoomRoom object.

2022-01-04 17:22 UTC, guymaness2 commented on ZoomDotNetFramework/Entities/Recurrence.cs
> +        public int Type { get; set; }
convert to enum

2022-01-04 17:24 UTC, guymaness2 commented on ZoomDotNetFramework/Entities/Recurrence.cs
> +        public int End_Date_Time { get; set; }
```suggestion
        public string End_Date_Time { get; set; }
```

2022-01-04 17:38 UTC, guymaness2 commented on ZoomDotNetFramework/ZoomApi.cs
> +    using rocks.kfs.ZoomRoom.Enums;
need to move enums to ZoomDotNetFramework assembly to avoid ref to KFS

2022-01-04 17:47 UTC, guymaness2 commented on ZoomDotNetFramework/ZoomApi.cs
> +            }
Add condition for setting pageSize

2022-01-04 17:55 UTC, guymaness2 commented on ZoomDotNetFramework/ZoomApi.cs
> +        public bool UpdateMeeting( Meeting meeting, string occurrenceId = null )
Re-test endpoint just to make sure it works

2022-01-04 18:10 UTC, guymaness2 commented on ZoomDotNetFramework/ZoomApi.cs
> +        public bool CancelZoomRoomMeeting( string roomId, string topic, DateTimeOffset startTime, string timezone, int duration )
Add meeting number as optional parameter for completeness

2022-01-04 18:27 UTC, guymaness2 commented on ZoomDotNetFramework/ZoomDotNetFramework.csproj
> +      <HintPath>..\..\RockWeb\Bin\RestSharp.dll</HintPath>
Switch to Nuget Package, making sure it is the same version as set on Rock

2022-01-04 18:27 UTC, guymaness2 commented on ZoomDotNetFramework/ZoomDotNetFramework.csproj
> +      <HintPath>..\..\packages\JWT.8.4.2\lib\net40\JWT.dll</HintPath>
making sure it is the same version as set on Rock

2022-01-04 18:28 UTC, guymaness2 commented on ZoomDotNetFramework/ZoomDotNetFramework.csproj
> +  <ItemGroup>
making sure all packages are the same version as set on Rock

2022-01-04 18:30 UTC, guymaness2 commented on ZoomDotNetFramework/app.config
> +        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
Make sure this updates to matching Rock version when changed

2022-01-06 16:43 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomMeetingGroupReminder.cs
> +        IsRequired = false,
```suggestion
        IsRequired = true,
```

2022-01-06 16:46 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomMeetingGroupReminder.cs
> +    [AttributeField(
Nate would like to see this one demonstrated

2022-01-06 16:52 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomMeetingGroupReminder.cs
> +            var systemEmailGuid = dataMap.GetString( AttributeKey.SystemCommunication ).AsGuid();
Change name of systemEmailGuid to systemCommunicationGuid

2022-01-06 16:53 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomMeetingGroupReminder.cs
> +            if ( jobPreferredCommunicationType != CommunicationType.Email && string.IsNullOrWhiteSpace( systemCommunication.SMSMessage ) )
need to take push into consideration

2022-01-06 17:00 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomMeetingGroupReminder.cs
> +            var endDate = dates.Max().AddDays( 1 );
change to add millisecond

2022-01-06 17:02 UTC, nateh777 commented on rocks.kfs.Zoom/Jobs/ZoomMeetingGroupReminder.cs
> +            var endDate = dates.Max().AddDays( 1 );
continue review from here.

2022-01-06 18:20 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomMeetingGroupReminder.cs
> +            var endDate = dates.Max().AddDays( 1 );
The logic is actually correct here. The dates being generated in the GetSearchDates are built from DateTime.Today, so they all cary the 12:00 AM time on them. These values are going to be compared to true DateTimes for the start times of the occurrences, so it is valid to add a day to the end date to check through midnight of the next day. If we wanted to be super precise, I guess I could do .AddDays( 1 ).AddMilliseconds( -1 ), but that might be a bit overkill.

2022-01-11 17:15 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomMeetingGroupReminder.cs
> +            var endDate = dates.Max().AddDays( 1 );
```suggestion
```

2022-01-11 17:35 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomMeetingGroupReminder.cs
> +                var groupAttributeValue = resLoc.Reservation.AttributeValues.FirstOrDefault( v => v.Key == resGroupAttribute.Key ).Value;
See if AttributeValues.GetAttributeValues() can be used here instead.

2022-01-11 17:37 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomMeetingGroupReminder.cs
> +            var occReminderInfo = new List<Tuple<Group, RoomOccurrence>>();
```suggestion
```

2022-01-11 17:41 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomMeetingGroupReminder.cs
> +                // if an exception occurs just use today's date.
Where's the beef?

2022-01-11 17:49 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomMeetingGroupReminder.cs
> +                            smsMessage.AddRecipient( new RockSMSMessageRecipient( groupMember.Person, smsNumber, mergeFields ) );
needs wrapped in else

2022-01-11 17:49 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomMeetingGroupReminder.cs
> +                            pushMessage.AddRecipient( new RockPushMessageRecipient( groupMember.Person, deviceIds, mergeFields ) );
wrap in else

2022-01-11 17:52 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomMeetingGroupReminder.cs
> +                                errorMessages.Add( string.Format( "No devices that support notifications could be found for {0}.", groupMember.Person.FullName ) );
Add goto case for Email

2022-01-11 17:53 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomMeetingGroupReminder.cs
> +                                errorMessages.Add( string.Format( "No SMS number could be found for {0}.", groupMember.Person.FullName ) );
add goto case for email

2022-01-11 17:54 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomMeetingGroupReminder.cs
> +                    pushMessage.Send( out errorsSms );
fix out variable to be push errors

2022-01-11 17:56 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomMeetingGroupReminder.cs
> +                    if ( !groupMember.Person.CanReceiveEmail( false ) && smsNumber.IsNullOrWhiteSpace() )
can we add a condition for person with no push capabilities?

2022-01-18 17:15 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomMeetingGroupReminder.cs
> +                if ( !string.IsNullOrEmpty( groupAttributeValue ) )
```suggestion
                if ( !string.IsNullOrWhiteSpace( groupAttributeValue ) )
```

2022-01-18 17:30 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +                var strng = "What do I do here?";
Log an error here

2022-01-18 17:33 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +                var logService = new ServiceLogService( rockContext );
Is this still used?

2022-01-18 17:35 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +                                                 .WhereAttributeValue( rockContext, a => a.Attribute.Key == "KFSZoomRoom" && a.Value != null && a.Value != "" )
Fully qualify attribute key with "rocks.kfs.blah.blah". Propagate through code

2022-01-18 17:37 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +                    var zoomRoomDT = DefinedValueCache.Get( loc.AttributeValues.FirstOrDefault( v => v.Key == "KFSZoomRoom" ).Value.Value.AsGuid() );
Rename to zoomRoomDV (since it is defined values). Also change loc.AttributeValues to GetAttributeValues

2022-01-18 17:40 UTC, nateh777 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +                                                                .Where( ro => ro.IsCompleted == false
Formatting. The `.` from each line should match up to each other.

2022-01-18 17:40 UTC, nateh777 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +                                                                .Where( ro => ro.EntityTypeId == reservationLocationEntityTypeId
Formatting. The `.` from each line should match up to each other.

2022-01-18 17:50 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +                if ( zoomImportReservationType == null )
handled in migration

2022-01-18 17:58 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +                                scheduleService.Add( schedule );
might need to add context.SaveChanges() to save the schedule before moving on.

2022-01-18 18:01 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +                                    ScheduleId = schedule.Id,
Can full schedule entity be set here? If not, need to save schedule before we get here.

2022-01-18 18:01 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +                                    EntityId = reservationLocation.Id,
Can full schedule entity be set here? If not, need to save reservationLocation before we get here.

2022-01-18 18:04 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +                            rockContext.SaveChanges();
needs to move to follow line 306

2022-01-18 18:12 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +                        var zoomRoomDT = DefinedValueCache.Get( rl.Location.AttributeValues.FirstOrDefault( v => v.Key == "KFSZoomRoom" ).Value.Value.AsGuid() );
change to zoomRoomDV

2022-01-18 18:13 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +                        var zrPassword = zoomRoomDT.AttributeValues.FirstOrDefault( v => v.Key == "ZoomMeetingPassword" ).Value.Value;
Use GetAttributeValue

2022-01-18 18:13 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +                        var joinBeforeHost = zoomRoomDT.AttributeValues.FirstOrDefault( v => v.Key == "ZoomJoinBeforeHost" ).Value.Value.AsBoolean();
Use GetAttributeValue

2022-01-18 18:17 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +                        locationIdsToProcess.Add( rl.Id );
rename resLocationIdsToProcess

2022-01-18 18:33 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +                rockContext.SaveChanges();
Move above line 489

2022-01-18 18:34 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +                LogEvent( rockContext, "Zoom Room Reservation Sync", string.Format( "{0} Zoom meeting(s) to delete.", occurrencesToCancel.Count() ) );
pass null for rockContext of all LogEvent calls so it will create its own context

2022-01-18 18:37 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +                        LogEvent( rockContext, "Zoom Room Reservation Sync", string.Format( "Begin create new Zoom Meeting: ZoomRoom {0} - {1}", roomId, occurrence.StartTime.ToShortDateTimeString() )
probably don't want to pass in context here

2022-01-18 18:38 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +                    var newMeeting = zoom.CreateZoomMeeting( roomId, meetingToCreate );
Should this be ScheduleMeeting

2022-01-18 18:40 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +            var rockLogger = new ServiceLogService( rockContext );
Need to support null rockContext coming in and generate a new context in that scenario

2022-01-18 18:40 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +                Name = "Eventbrite",
Ooops!

2022-01-20 17:00 UTC, guymaness2 commented on rocks.kfs.Zoom/Migrations/001_CreateDb.cs
> +                REFERENCES [dbo].[Schedule] ([Id])
add on delete cascade

2022-01-20 17:09 UTC, guymaness2 commented on rocks.kfs.Zoom/Migrations/001_CreateDb.cs
> +                SET @AllUsersGroupId = (SELECT [Id] FROM [Group] WHERE [Guid] = '{4}')
```suggestion
```

2022-01-20 17:21 UTC, guymaness2 commented on rocks.kfs.Zoom/Migrations/002_CreateAttributes.cs
> +            RockMigrationHelper.UpdateFieldType( "Zoom Room", "", "rocks.kfs.Zoom", "rocks.kfs.Zoom.Field.Types.ZoomMeetingFieldType", ZoomGuid.FieldType.ZOOM_MEETING );
Are these needed?

2022-01-20 17:22 UTC, guymaness2 commented on rocks.kfs.Zoom/Migrations/002_CreateAttributes.cs
> +            RockMigrationHelper.UpdateEntityType( "rocks.kfs.Zoom.ZoomApp", "Zoom App", "", false, true, ZoomGuid.EntityType.ZOOM );
Why the need to use a different override than what is used on EventBrite?

2022-01-20 17:25 UTC, guymaness2 commented on rocks.kfs.Zoom/Migrations/002_CreateAttributes.cs
> +            RockMigrationHelper.AddNewEntityAttribute( "rocks.kfs.Zoom.ZoomApp", Rock.SystemGuid.FieldType.ENCRYPTED_TEXT, "", "", "API Secret", "", "The API Secret for the Zoom Marketplace JWT app t
Update attribute key names using current convention and propagate

2022-01-20 17:28 UTC, guymaness2 commented on rocks.kfs.Zoom/Migrations/002_CreateAttributes.cs
> +                RockMigrationHelper.AddNewEntityAttribute( "com.bemaservices.RoomManagement.Model.Reservation", Rock.SystemGuid.FieldType.GROUP_TYPE_GROUP, "", "", "Zoom Notify Group", "", "The Group
update attribute key to naming convention

2022-01-20 17:40 UTC, guymaness2 commented on rocks.kfs.Zoom/Migrations/002_CreateAttributes.cs
> +            RockMigrationHelper.AddDefinedTypeAttribute( ZoomGuid.DefinedType.ZOOM_ROOM, Rock.SystemGuid.FieldType.TEXT, "User PMI", "ZoomUsersPMI", "Zoom user's personal meeting ID. NOTE: Must be nu
These appear to not be useable. Consider removing

2022-01-20 17:40 UTC, guymaness2 commented on rocks.kfs.Zoom/Migrations/002_CreateAttributes.cs
> +            RockMigrationHelper.AddDefinedTypeAttribute( ZoomGuid.DefinedType.ZOOM_ROOM, Rock.SystemGuid.FieldType.TEXT, "Time Zone", "ZoomMeetingTimeZone", "Zoom meeting time zone. A list of valid t
This appears to not be useable. Consider removing

2022-01-20 17:43 UTC, guymaness2 commented on rocks.kfs.Zoom/Migrations/002_CreateAttributes.cs
> +            RockMigrationHelper.AddDefinedTypeAttribute( ZoomGuid.DefinedType.ZOOM_ROOM, Rock.SystemGuid.FieldType.TEXT, "Time Zone", "ZoomMeetingTimeZone", "Zoom meeting time zone. A list of valid t
update attribute key to naming convention

2022-01-20 17:43 UTC, guymaness2 commented on rocks.kfs.Zoom/Migrations/002_CreateAttributes.cs
> +            RockMigrationHelper.AddOrUpdateEntityAttribute( "Rock.Model.Location", Rock.SystemGuid.FieldType.DEFINED_VALUE, "", "", "Zoom Room", "", "The Zoom Room associated with this location.", 0,
update attribute key to naming convention

2022-01-20 17:47 UTC, guymaness2 commented on rocks.kfs.Zoom/Migrations/002_CreateAttributes.cs
> +            RockMigrationHelper.AddOrUpdateEntityAttribute( "Rock.Model.Location", Rock.SystemGuid.FieldType.DEFINED_VALUE, "", "", "Zoom Room", "", "The Zoom Room associated with this location.", 0,
This appears to lack definition of which defined type to use for the attribute. Need to look into and verify.

2022-01-20 17:50 UTC, guymaness2 commented on rocks.kfs.Zoom/Migrations/002_CreateAttributes.cs
> +            RockMigrationHelper.DeleteAttribute( ZoomGuid.Attribute.ZOOM_MEETING_TIME_ZONE );
Not needed if attribute removed from previous comment

2022-01-20 17:52 UTC, guymaness2 commented on rocks.kfs.Zoom/Migrations/002_CreateAttributes.cs
> +            RockMigrationHelper.DeleteAttribute( "4B6E0AF2-9D9D-4801-B8CE-F2B424F970FE" );
This doesn't appear to exist.

2022-01-20 17:52 UTC, guymaness2 commented on rocks.kfs.Zoom/Migrations/002_CreateAttributes.cs
> +            RockMigrationHelper.DeleteFieldType( ZoomGuid.FieldType.ZOOM_ROOM );
If field types are not used, remove these

2022-01-25 18:24 UTC, guymaness2 commented on rocks.kfs.Zoom/Migrations/002_CreateAttributes.cs
> +            RockMigrationHelper.UpdateEntityType( "rocks.kfs.Zoom.ZoomApp", "Zoom App", "", false, true, ZoomGuid.EntityType.ZOOM );
I'm pretty sure the reason I used this override is to be able to set the "FriendlyName" property of the Entity Type as it displays in the migrated UI elements.

2022-01-27 17:16 UTC, guymaness2 commented on rocks.kfs.Zoom/Migrations/002_CreateAttributes.cs
> +            RockMigrationHelper.AddDefinedTypeAttribute( ZoomGuid.DefinedType.ZOOM_ROOM, Rock.SystemGuid.FieldType.TEXT, "Meeting Password", "rocks.kfs.ZoomMeetingPassword", "Zoom meeting password.",
fix order

2022-01-27 17:17 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +                    var zoomRoomDT = DefinedValueCache.Get( loc.AttributeValues.FirstOrDefault( v => v.Key == "rocks.kfs.KFSZoomRoom" ).Value.Value.AsGuid() );
remove redundant "KFS" from front of attribute keys

2022-01-27 17:39 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +        private void CreateOccurrenceZoomMeeting( RoomOccurrence occurrence, string zoomRoomId, bool joinBeforeHost, out bool changesMade )
Switch from using output parameter to returning bool. Make sure to provide good ghost doc summary to explain he return

2022-01-27 17:40 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +                    var changesMade = false;
looks half baked. Make sure to flesh it out

2022-01-27 17:49 UTC, guymaness2 commented on rocks.kfs.Zoom/Migrations/005_CreateJobs.cs
> +                  ,'0 0 4 1/1 * ? *'  -- Daily at 4:00 AM
Change to every hour

2022-01-27 18:15 UTC, guymaness2 commented on rocks.kfs.Zoom/Migrations/007_DataViewsAndReports.cs
> +            // Add GUID to Reporting DataSelect entity type for reporting: Location Name
Can this be done with helpers instead?

2022-01-27 18:16 UTC, guymaness2 commented on rocks.kfs.Zoom/Migrations/007_DataViewsAndReports.cs
> +            Sql( @"DELETE FROM DataView where [Guid] = '45493469-8718-4C09-BB76-ED53AE3F2FA5'" );
Can we use helpers here?

2022-01-28 19:29 UTC, guymaness2 commented on rocks.kfs.Zoom/Migrations/007_DataViewsAndReports.cs
> +            Sql( @"DELETE FROM DataView where [Guid] = '45493469-8718-4C09-BB76-ED53AE3F2FA5'" );
no we cannot

2022-02-03 17:10 UTC, guymaness2 commented on rocks.kfs.Zoom/Migrations/007_DataViewsAndReports.cs
> +            RockMigrationHelper.AddReportField( "E89ED73D-3D1D-40EB-BC6A-5631C6BC9834", Rock.Model.ReportFieldType.DataSelectComponent, true, ZoomGuid.EntityType.REPORT_LOCATION_NAME, "{}", 5, "Locat
Should be order = 4

2022-02-03 17:11 UTC, guymaness2 commented on rocks.kfs.Zoom/Migrations/007_DataViewsAndReports.cs
> +            RockMigrationHelper.AddReportField( "E89ED73D-3D1D-40EB-BC6A-5631C6BC9834", Rock.Model.ReportFieldType.DataSelectComponent, true, ZoomGuid.EntityType.REPORT_ZOOM_ROOM_NAME, "{}", 6, "Zoom
Should be order = 5

2022-02-03 17:23 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +                    var deleteCount = orphanedOccurrences.Count();
not used

2022-02-03 17:26 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +                    CreateOccurrenceZoomMeeting( rOcc, zoomRoomDV.Value, joinBeforeHost, zoomRoomDV.Description );
pass full DV instead of just .Value and .Description

2022-02-03 17:26 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +                                if ( CreateOccurrenceZoomMeeting( occurrence, zoomRoomDV.Value, joinBeforeHost, zoomRoomDV.Description ) )
pass full DV instead of just .Value and .Description

2022-02-03 17:27 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +                            zrOccurrencesAdded += CreateZoomRoomOccurrences( zrOccurrenceService, zoomRoomDV.Value, res.Name, zrPassword, res.Schedule, joinBeforeHost, rl, reservationDateTimes, resLo
pass full DV instead of just .Value and .Description

2022-02-03 17:28 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +        private bool CreateOccurrenceZoomMeeting( RoomOccurrence occurrence, string zoomRoomId, bool joinBeforeHost, string zoomRoomName = null )
pass full DV instead of just .Value and .Description

2022-02-03 17:31 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +        private int CreateZoomRoomOccurrences( RoomOccurrenceService occService, string roomId, string occurrenceTopic, string password, Schedule schedule, bool joinBeforeHost, ReservationLocation re
pass full DV instead of just .Value and .Description

2022-02-03 17:32 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +                    CreateOccurrenceZoomMeeting( occurrence, roomId, joinBeforeHost, roomName );
pass full DV instead of just .Value and .Description

2022-02-03 17:37 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +                context.Result = "Zoom api authentication error. Check api settings for Zoom Room plugin or try again later.";
capitalize API

2022-02-03 17:37 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +                throw new Exception( "Authentication failed for Zoom api. Please verify the api settings configured in the Zoom Room plugin are valid and correct." );
capitalize API

2022-02-03 18:04 UTC, guymaness2 commented on rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
> +                        RowsAffected = 1,
Remove RowsAffected from everything.

2022-02-03 18:05 UTC, guymaness2 commented on rocks.kfs.Zoom/Model/RoomOccurrence.cs
> +// Copyright 2021 by Kingdom First Solutions
```suggestion
// Copyright 2022 by Kingdom First Solutions
```

2022-02-03 18:09 UTC, guymaness2 commented on rocks.kfs.Zoom/Model/RoomOccurrence.cs
> +        public bool IsOccurring { get; set; } = true;
Is this used

2022-02-03 18:10 UTC, guymaness2 commented on rocks.kfs.Zoom/Model/RoomOccurrence.cs
> +        public ZoomMeetingRequestStatus? ZoomMeetingRequestStatus { get; set; }
Is this added in the migration for the table?

2022-02-03 18:13 UTC, guymaness2 commented on rocks.kfs.Zoom/Model/RoomOccurrence.cs
> +            this.HasRequired( ro => ro.Location ).WithMany().HasForeignKey( cn => cn.LocationId ).WillCascadeOnDelete( false );
```suggestion
            this.HasRequired( ro => ro.Schedule ).WithMany().HasForeignKey( ro => ro.ScheduleId ).WillCascadeOnDelete( true );
            this.HasRequired( ro => ro.Location ).WithMany().HasForeignKey( cn => cn.LocationId ).WillCascadeOnDelete( true );
```

2022-02-03 18:21 UTC, guymaness2 commented on rocks.kfs.Zoom/Model/ScheduleMeetingWebhookResponse.cs
> +// Copyright 2021 by Kingdom First Solutions
update copyright everywhere

2022-02-03 18:22 UTC, guymaness2 commented on rocks.kfs.Zoom/Properties/AssemblyInfo.cs
> +﻿using System.Reflection;
missing copyright summary

2022-02-03 18:23 UTC, guymaness2 commented on rocks.kfs.Zoom/Reporting/RoomOccurrence/DataSelect/LocationName.cs
> +﻿
missing copyright summary

2022-02-03 18:26 UTC, guymaness2 commented on rocks.kfs.Zoom/Reporting/RoomOccurrence/DataSelect/LocationName.cs
> +            var occurrenceQuery = new RoomOccurrenceService( context ).Queryable();
```suggestion
            var occurrenceQuery = new RoomOccurrenceService( context ).Queryable( "Location" );
```

2022-02-03 18:40 UTC, guymaness2 commented on rocks.kfs.Zoom/Reporting/RoomOccurrence/DataSelect/ReservationNotifyGroup.cs
> +                .Select( ro => groupQuery.FirstOrDefault( g => resGroupAttValues.FirstOrDefault( v => reservationQuery.FirstOrDefault( r => reservationlocationQuery.FirstOrDefault( rl => ro.EntityTyp
Nate thinking about possible null handling

2022-02-03 18:42 UTC, guymaness2 commented on rocks.kfs.Zoom/Reporting/RoomOccurrence/DataSelect/ScheduleEndDate.cs
> +            var occurrenceQuery = new RoomOccurrenceService( context ).Queryable();
```suggestion
            var occurrenceQuery = new RoomOccurrenceService( context ).Queryable( "Schedule" );
```

2022-02-03 18:44 UTC, guymaness2 commented on rocks.kfs.Zoom/Reporting/RoomOccurrence/DataSelect/ScheduleEndDate.cs
> +            scheduleQuery = occurrenceQuery.Select( ro => ro.Schedule.EffectiveEndDate.Value.ToShortDateString() );
Do we want this to be limited to date only? Consider removing ToShortDateString conversion

2022-02-03 18:45 UTC, guymaness2 commented on rocks.kfs.Zoom/Reporting/RoomOccurrence/DataSelect/ScheduleName.cs
> +            var occurrenceQuery = new RoomOccurrenceService( context ).Queryable();
```suggestion
            var occurrenceQuery = new RoomOccurrenceService( context ).Queryable( "Schedule" );
```

2022-02-03 18:46 UTC, guymaness2 commented on rocks.kfs.Zoom/Reporting/RoomOccurrence/DataSelect/ScheduleStartDate.cs
> +            var occurrenceQuery = new RoomOccurrenceService( context ).Queryable();
```suggestion
            var occurrenceQuery = new RoomOccurrenceService( context ).Queryable( "Schedule" );
```

2022-02-03 18:47 UTC, guymaness2 commented on rocks.kfs.Zoom/Reporting/RoomOccurrence/DataSelect/ScheduleStartDate.cs
> +            scheduleQuery = occurrenceQuery.Select( ro => ro.Schedule.EffectiveStartDate.Value.ToShortDateString() );
Do we want this to be limited to date only? Consider removing ToShortDateString conversion

2022-02-03 18:51 UTC, guymaness2 commented on rocks.kfs.Zoom/Reporting/RoomOccurrence/DataSelect/ZoomRoomId.cs
> +            var valuesQuery = serviceInstance.Queryable()
```suggestion
            var valuesQuery = serviceInstance.Queryable( "Attribute" )
```

2022-02-03 18:52 UTC, guymaness2 commented on rocks.kfs.Zoom/Reporting/RoomOccurrence/DataSelect/ZoomRoomId.cs
> +                .Select( x => new { EntityId = x.EntityId, Value = x.Value } );
are the definition statements needed?

2022-02-03 18:58 UTC, guymaness2 commented on rocks.kfs.Zoom/Reporting/RoomOccurrence/DataSelect/ZoomRoomName.cs
> +    [Description( "Show Zoom Room Id" )]
```suggestion
    [Description( "Show Zoom Room Name" )]
```

2022-02-03 18:58 UTC, guymaness2 commented on rocks.kfs.Zoom/Reporting/RoomOccurrence/DataSelect/ZoomRoomName.cs
> +    [ExportMetadata( "ComponentName", "Select Zoom Room Id" )]
```suggestion
    [ExportMetadata( "ComponentName", "Select Zoom Room Name" )]
```

2022-02-03 18:59 UTC, guymaness2 commented on rocks.kfs.Zoom/Reporting/RoomOccurrence/DataSelect/ZoomRoomName.cs
> +            var valuesQuery = serviceInstance.Queryable()
```suggestion
            var valuesQuery = serviceInstance.Queryable( "Attribute" )
```

2022-02-22 17:25 UTC, nateh777 commented on rocks.kfs.Zoom/Field/Types/ZoomRoomFieldType.cs
> +    public class ZoomRoomFieldType : FieldType
Is this necessary? What is this for?

2022-02-22 17:29 UTC, guymaness2 commented on rocks.kfs.Zoom/Reporting/RoomOccurrence/DataSelect/ScheduleEndDate.cs
> +            scheduleQuery = occurrenceQuery.Select( ro => ro.Schedule.EffectiveEndDate.Value );
need to verify if tested

2022-02-22 17:31 UTC, guymaness2 commented on rocks.kfs.Zoom/Settings.cs
> +﻿using JWT.Algorithms;
Missing licensing summary

2022-02-22 17:40 UTC, guymaness2 commented on rocks.kfs.Zoom/Utility/ExtensionMethods/StringExtensions.cs
> +﻿using System.Text;
This class is not being used. Delete it

2022-02-22 17:47 UTC, guymaness2 commented on rocks.kfs.Zoom/Zoom.cs
> +                LogEvent( rockContext, "SyncZoom", "Remove Defined Values for Zoom Rooms that no longer exist.", string.Format( "Deleted {0} Zoom Room Defined Value(s).", zoomRoomsToDelete.Count() )
null rockContext out

2022-02-22 17:50 UTC, guymaness2 commented on rocks.kfs.Zoom/app.config
> +﻿<?xml version="1.0" encoding="utf-8"?>
try removing this file

2022-02-22 17:51 UTC, guymaness2 commented on rocks.kfs.Zoom/rocks.kfs.Zoom.csproj
> +    <Deterministic>true</Deterministic>
```suggestion
    <Deterministic>false</Deterministic>
```

2022-02-22 17:51 UTC, nateh777 commented on rocks.kfs.Zoom/Properties/AssemblyInfo.cs
> +// [assembly: AssemblyVersion("1.0.*")]
Let's change to wildcard version to match other assemblies.

2022-02-22 17:56 UTC, guymaness2 commented on rocks.kfs.Zoom/rocks.kfs.Zoom.csproj
> +    <Reference Include="com.bemaservices.RoomManagement">
Create a libs folder under KFSRockAssemblies and move this file and reference there. Also update RoomManagement.Templates project reference to point to the same.

2022-02-22 22:46 UTC, guymaness2 commented
@nateh777 after going back through, I found several unresolved conversations that I apparently missed. This request has been fully scrubbed, with all conversations resolved save the last 2 that indicate input desired from you. This scrub did result  in a few more code changes than expected. Some from previously missed conversations, and a couple from debugging after testing out a few areas.

2022-02-24 16:35 UTC, nateh777 requested changes
A few minor comments, but we are almost there!

2022-02-24 16:35 UTC, nateh777 commented on rocks.kfs.RoomManagement.Templates/rocks.kfs.RoomManagement.ReportTemplates.csproj
> +      <HintPath>..\..\..\KFSRockAssemblies\libs\com.bemaservices.RoomManagement.dll</HintPath>
```suggestion
      <HintPath>..\libs\com.bemaservices.RoomManagement.dll</HintPath>
```

2022-02-24 16:35 UTC, nateh777 commented on rocks.kfs.Zoom/Reporting/RoomOccurrence/DataSelect/ScheduleEndDate.cs
> +            scheduleQuery = occurrenceQuery.Select( ro => ro.Schedule.EffectiveEndDate );
Since this was titled "to make report fields work" that you tested this? Can you add some screenshots of the reports?

2022-02-24 16:35 UTC, nateh777 commented on rocks.kfs.Zoom/rocks.kfs.Zoom.csproj
> +      <HintPath>..\..\..\KFSRockAssemblies\libs\com.bemaservices.RoomManagement.dll</HintPath>
```suggestion
      <HintPath>..\libs\com.bemaservices.RoomManagement.dll</HintPath>
```

2022-02-24 16:35 UTC, nateh777 commented on rocks.kfs.RoomManagement.Templates/rocks.kfs.RoomManagement.ReportTemplates.csproj
> +      <HintPath>..\..\..\KFSRockAssemblies\libs\com.bemaservices.RoomManagement.dll</HintPath>
Can you also move itextsharp.dll out of the libs folder within the project, move it to the top level, and delete the libs folder in this project?

2022-02-24 16:48 UTC, nateh777 commented on rocks.kfs.Zoom/Reporting/RoomOccurrence/DataSelect/ReservationNotifyGroup.cs
> +                .Select( ro => groupQuery.FirstOrDefault( g => resGroupAttValues.FirstOrDefault( v => reservationQuery.FirstOrDefault( r => reservationlocationQuery.FirstOrDefault( rl => ro.EntityTyp
@guymaness2 See if you can use the null propagation operator here, for ReserverationId, Id, Value and GroupName
https://www.c-sharpcorner.com/UploadFile/16101a/null-propagation-operator-a-new-feature-of-C-Sharp-6-0/

2022-02-24 16:55 UTC, nateh777 commented on rocks.kfs.Zoom/Jobs/ZoomMeetingGroupReminder.cs
> +    [AttributeField(
@guymaness2 can you make sure you tested the group reminder and can you provide screenshots of the emails coming through? Not sure what else I wanted demonstrated but I think that is all I had.

2022-02-24 16:58 UTC, nateh777 commented
I also responded to existing conversations that were still open, not sure if that will show in changes or not.

2022-02-24 17:10 UTC, guymaness2 commented on rocks.kfs.Zoom/Reporting/RoomOccurrence/DataSelect/ScheduleEndDate.cs
> +            scheduleQuery = occurrenceQuery.Select( ro => ro.Schedule.EffectiveEndDate );
@nateh777 Correct, I tested it. Below is a screenshot. That being said, I did notice that the Start Time field comes in as a date only vs. date time. That is pulled in as a default property from the RoomOccurrence object, so I don't know if/how it can be changed to display date and time. 
![image](https://user-images.githubusercontent.com/7374281/155572986-018ee1f5-9534-4a68-8a1e-28d57d4e9e20.png)

2022-02-24 17:13 UTC, nateh777 commented on rocks.kfs.Zoom/Reporting/RoomOccurrence/DataSelect/ScheduleEndDate.cs
> +            scheduleQuery = occurrenceQuery.Select( ro => ro.Schedule.EffectiveEndDate );
Is it stored in the schedule/database with an actual time? That seems odd that it comes in with 12:00 AM if it is stored with an actual time

2022-02-24 20:14 UTC, guymaness2 commented on rocks.kfs.Zoom/Reporting/RoomOccurrence/DataSelect/ReservationNotifyGroup.cs
> +                .Select( ro => groupQuery.FirstOrDefault( g => resGroupAttValues.FirstOrDefault( v => reservationQuery.FirstOrDefault( r => reservationlocationQuery.FirstOrDefault( rl => ro.EntityTyp
@nateh777  it doesn't look like it will work, unless I am missing your thought on how to use it 
![image](https://user-images.githubusercontent.com/7374281/155600313-e911ed18-8e85-4639-82fc-d5fe0dfa9644.png)

2022-02-24 21:14 UTC, nateh777 commented on rocks.kfs.Zoom/Reporting/RoomOccurrence/DataSelect/ReservationNotifyGroup.cs
> +                .Select( ro => groupQuery.FirstOrDefault( g => resGroupAttValues.FirstOrDefault( v => reservationQuery.FirstOrDefault( r => reservationlocationQuery.FirstOrDefault( rl => ro.EntityTyp
@guymaness2 well that is unfortunate, that is exactly how I was thinking of using it. because to do it "properly"/in lambda it would require a dual check on every one of your firstordefault and that just seems like that would be very cluttered to do... I am just a bit concerned if any of them could be null though. 

i.e. `reservationlocationQuery.FirstOrDefault( rl => ro.EntityTypeId == reservationLocationEntityTypeId && rl.Id == ro.EntityId ).ReservationId == r.Id ` turns into `reservationlocationQuery.FirstOrDefault( rl => ro.EntityTypeId == reservationLocationEntityTypeId && rl.Id == ro.EntityId ) != null && reservationlocationQuery.FirstOrDefault( rl => ro.EntityTypeId == reservationLocationEntityTypeId && rl.Id == ro.EntityId ).ReservationId == r.Id` and it is exponential per level

I feel like there has to be a better way to do that, but I am coming up blank on how I would...

2022-02-24 23:53 UTC, nateh777 approved these changes

2022-02-24 23:53 UTC, merged