Custom Group Reminder Emails
KingdomFirst/RockAssemblies pull request #86
Opened 2022-08-11 22:23 UTC by mattbaylor

### Description 

Adds a job that allows for custom reminder emails to be sent on a group by group basis

**New Settings:**

* System Communication - System communication to be used for the reminder
* Send Using - Communication Transport to be used for the reminder
* Group Attribute - The attribute on the group that must be set to true to trigger the reminder
---------

### Release Notes 

New Job that will send reminders to a group based on the Job schedule as long as they are marked with a configured group attribute of type boolean that is set to true.

---------

### Requested By

CBC - Neenah

---------

### Screenshots

![image](https://user-images.githubusercontent.com/2577926/184252341-5cc99978-7198-4128-ba4b-e0a7e3dee85e.png)

---------

### Change Log

* rocks.kfs.CustomGroupCommunication/Jobs/MeetingGroupReminder.cs - Job
* rocks.kfs.CustomGroupCommunication/Properties/AssemblyInfo.cs - Project definition
* rocks.kfs.CustomGroupCommunication/rocks.kfs.CustomGroupCommunication.csproj - Project Definition

---------

### Migrations/External Impacts

No

2022-08-12 23:23 UTC, nateh777 requested changes
@mattbaylor had a chance to review, though I thought I might not, there are some significant changes needed still. Please let me know if you need help with any of them and we can look at it together if need be.

2022-08-12 23:23 UTC, nateh777 commented on rocks.kfs.CustomGroupCommunication/Jobs/MeetingGroupReminder.cs
> +        DefaultValue = Rock.SystemGuid.SystemCommunication.SCHEDULING_REMINDER,
We should probably consider creating our own default system communication for this since this job relies on a communication and there are no system defaults that are appropriate for this. We have various examples of migrations that do so. Including the job this was based off of.

2022-08-12 23:23 UTC, nateh777 commented on rocks.kfs.CustomGroupCommunication/Jobs/MeetingGroupReminder.cs
> +        Description = "The Group Attribute where we will look for the set value",
```suggestion
        Description = "The Group Attribute where we will look for the set value. We recommend a Boolean field type attribute.",
```

2022-08-12 23:23 UTC, nateh777 commented on rocks.kfs.CustomGroupCommunication/Jobs/MeetingGroupReminder.cs
> +
```suggestion
```

2022-08-12 23:23 UTC, nateh777 commented on rocks.kfs.CustomGroupCommunication/Jobs/MeetingGroupReminder.cs
> +                    $"The Custom Communication Group Attribute job setting is invalid. Please check your Custom Communication job configuration."
This error needs to be re-written. Should be Group meeting reminder specific and maybe something about groups not being found. In fact, will this error ever be encountered? Can you produce a scenario to test it? Perhaps we should have a `groups.Any()` check on this as well?

2022-08-12 23:23 UTC, nateh777 commented on rocks.kfs.CustomGroupCommunication/Jobs/MeetingGroupReminder.cs
> +        /// <param name="jobPreferredCommunicationType">Type of the job preferred communication.</param>
Update parameters in Ghostdoc.

2022-08-12 23:23 UTC, nateh777 commented on rocks.kfs.CustomGroupCommunication/Jobs/MeetingGroupReminder.cs
> +            foreach ( var group in groups )
It seems the logic was removed from somewhere that did the **Days Prior** calculation, this will just send meeting reminders all the time, it needs to calculate when to send reminders based on the group's schedule. and the `Days Prior` setting. I was hoping it was straight forward from the Zoom meeting reminder, but perhaps it is not due to it using room occurrences. Perhaps see logic in https://github.com/KingdomFirst/RockAssemblies/blob/master/rocks.kfs.GroupRoleAttendanceReminder/Jobs/GroupRoleSendAttendanceReminders.cs#L117-L188 instead. However, keep in mind that the attendance entry reminder was Days _After_ the group meets, but the calculation should be similar.

2022-08-12 23:23 UTC, nateh777 commented on rocks.kfs.CustomGroupCommunication/Properties/AssemblyInfo.cs
> +// Copyright 2019 by Kingdom First Solutions
```suggestion
// Copyright 2022 by Kingdom First Solutions
```

2022-08-17 15:22 UTC, mattbaylor commented on rocks.kfs.CustomGroupCommunication/Jobs/MeetingGroupReminder.cs
> +        DefaultValue = Rock.SystemGuid.SystemCommunication.SCHEDULING_REMINDER,
custom communication created

2022-08-17 15:23 UTC, mattbaylor commented on rocks.kfs.CustomGroupCommunication/Jobs/MeetingGroupReminder.cs
> +                    $"The Custom Communication Group Attribute job setting is invalid. Please check your Custom Communication job configuration."
this state is not reachable or testable. Removed.

2022-08-17 15:23 UTC, mattbaylor commented on rocks.kfs.CustomGroupCommunication/Jobs/MeetingGroupReminder.cs
> +            foreach ( var group in groups )
Days prior added back in.

2022-08-17 17:21 UTC, mattbaylor reviewed
All issues adjusted..

2022-08-18 20:59 UTC, nateh777 commented on rocks.kfs.CustomGroupCommunication/Jobs/MeetingGroupReminder.cs
> +                    mergeFields.Add( "NextMeetingDates", string.Join( "    ", meetingDates ) );
@mattbaylor can you explain why it changed to NextMeetingDates? Does it pull in multiple now? I would think it would still be only one date based on the logic, isn't it? Can you show me a screenshot of the email, and actually that wouldn't be bad to add to the request anyway.

2022-08-18 21:14 UTC, mattbaylor commented on rocks.kfs.CustomGroupCommunication/Jobs/MeetingGroupReminder.cs
> +                    mergeFields.Add( "NextMeetingDates", string.Join( "    ", meetingDates ) );
Because there are multiple days prior now it's possible that a group has a meeting on each of the dates. That would result in multiple meetings per job run. Rather than sending a reminder per meeting, I'm just putting both dates into the email. Screenshot of the email is added to the description.

2022-08-18 21:24 UTC, nateh777 approved these changes

2022-08-18 21:24 UTC, merged